// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SparkFlow.Server.Infrastructure.Persistence;

#nullable disable

namespace SparkFlow.Server.Migrations
{
    [DbContext(typeof(SparkFlowDbContext))]
    [Migration("20260317012903_MigrateSessionsToPostgres")]
    partial class MigrateSessionsToPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("FailureCount")
                        .HasColumnType("integer")
                        .HasColumnName("failure_count");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_id");

                    b.Property<DateTime?>("LastRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at_utc");

                    b.Property<bool>("Locked")
                        .HasColumnType("boolean")
                        .HasColumnName("locked");

                    b.Property<string>("LockedBySessionId")
                        .HasColumnType("text")
                        .HasColumnName("locked_by_session_id");

                    b.Property<DateTime>("NextRunAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NextRunAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("accounts", "public");
                });

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.FlowEnvelope", b =>
                {
                    b.Property<string>("FlowId")
                        .HasColumnType("text")
                        .HasColumnName("flow_id");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signature");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.HasKey("FlowId");

                    b.ToTable("flows", "public");
                });

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.LogEvent", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp_utc");

                    b.HasKey("id");

                    b.ToTable("logs", "public");
                });

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.Policy", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("cooldown_minutes");

                    b.Property<int>("FailureThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("failure_threshold");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxRunsPerDay")
                        .HasColumnType("integer")
                        .HasColumnName("max_runs_per_day");

                    b.Property<int>("PauseDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("pause_duration_minutes");

                    b.HasKey("Id");

                    b.ToTable("policies", "public");
                });

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTime?>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FlowId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_id");

                    b.Property<int>("FlowVersion")
                        .HasColumnType("integer")
                        .HasColumnName("flow_version");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("Status");

                    b.ToTable("sessions", "public");
                });

            modelBuilder.Entity("SparkFlow.Server.Domain.Entities.WorkerNode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CurrentSessionId")
                        .HasColumnType("text")
                        .HasColumnName("current_session_id");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at_utc");

                    b.Property<string>("LastSeenIp")
                        .HasColumnType("text")
                        .HasColumnName("last_seen_ip");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("machine_id");

                    b.Property<int>("MaxConcurrentSessions")
                        .HasColumnType("integer")
                        .HasColumnName("max_concurrent_sessions");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("workers", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
